# Generated by Django 4.2.5 on 2023-11-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_billingmenuproduct_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='delivery_price',
            field=models.CharField(default='Бесплатно', max_length=100, verbose_name='Цена доставки'),
        ),
    ]
