# Generated by Django 4.2.5 on 2023-11-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Внешний ID'),
        ),
    ]
