# Generated by Django 4.2.5 on 2023-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=9999, verbose_name='Приоритет категории'),
        ),
    ]
