# Generated by Django 4.2.5 on 2023-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет категории'),
        ),
    ]
