# Generated by Django 4.2.5 on 2024-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Промокод'),
        ),
    ]
