# Generated by Django 4.2.5 on 2024-01-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма скидки'),
        ),
    ]
