# Generated by Django 4.2.5 on 2023-10-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='menu_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table', verbose_name='Стол'),
        ),
    ]
