# Generated by Django 4.2.5 on 2024-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_tableorder_menu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='promo_code',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Промокод'),
        ),
    ]
