# Generated by Django 4.2.5 on 2024-01-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='user_images/', verbose_name='Фотография профиля'),
        ),
    ]
