# Generated by Django 4.2.5 on 2023-12-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_visits', models.IntegerField(default=0, verbose_name='Количество посещений сайта (Главная)')),
                ('count_visits_menu', models.IntegerField(default=0, verbose_name='Количество посещений сайта (Меню)')),
            ],
        ),
    ]
