# Generated by Django 4.2.5 on 2023-12-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_statistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистики'},
        ),
    ]
