# Generated by Django 4.2.5 on 2024-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_statistics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Мобильное лого'),
        ),
    ]
