# Generated by Django 4.2.5 on 2024-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_setting_mobile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
    ]
