# Generated by Django 4.2.5 on 2024-01-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_setting_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемый вопросы',
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='promotions_image/', verbose_name='Фотография')),
                ('url', models.URLField(verbose_name='Ссылка на промоакцию')),
            ],
            options={
                'verbose_name': 'Промоакция',
                'verbose_name_plural': 'Промоакции',
            },
        ),
    ]
