# Generated by Django 4.2.5 on 2024-01-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_faq_promotions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
    ]
