# Generated by Django 4.2.5 on 2024-01-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_faq_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('quantity', models.SmallIntegerField(verbose_name='Количество')),
                ('amount', models.IntegerField(verbose_name='Сумма промокода')),
            ],
            options={
                'verbose_name': 'Промокод (скидка на сайте)',
                'verbose_name_plural': 'Промокоды (скидки на сайте)',
            },
        ),
    ]
