# Generated by Django 4.2.5 on 2024-01-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='city_modal',
            field=models.BooleanField(blank=True, default=False, help_text='Если значение True, то выводится окошко для выбора города', null=True, verbose_name='Всплывающее окно в главной странице'),
        ),
        migrations.AddField(
            model_name='setting',
            name='main_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Основной город'),
        ),
        migrations.CreateModel(
            name='SettingCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название города')),
                ('url', models.URLField(verbose_name='Ссылка на город')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_cities', to='settings.setting', verbose_name='Настройка')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
