# Generated by Django 4.2.5 on 2024-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_setting_city_modal_setting_main_city_settingcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='menu_telegram_group_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID чата menu telegram'),
        ),
        migrations.AddField(
            model_name='setting',
            name='telegram_group_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID чата telegram'),
        ),
    ]
