# Generated by Django 4.2.5 on 2023-12-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_telegram', '0002_alter_telegramuser_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Пользователь')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_support', to='my_telegram.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение Техподдержку',
                'verbose_name_plural': 'Обращения Техподдержки',
            },
        ),
    ]
