# Generated by Django 4.2.5 on 2023-12-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_telegram', '0003_technicalsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupport',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
