# Generated by Django 4.2.5 on 2023-12-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_telegram', '0004_technicalsupport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupport',
            name='message',
            field=models.CharField(blank=True, default='Пользователь не оставил сообщение', max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='technicalsupport',
            name='support_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_operator_user', to='my_telegram.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='technicalsupport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
