# Generated by Django 4.2.5 on 2023-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_telegram', '0007_alter_technicalsupport_support_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupport',
            name='support_assessment',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка поддержки'),
        ),
    ]
